#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNdb")]
	public partial class UNClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmedcin_info(medcin_info instance);
    partial void Updatemedcin_info(medcin_info instance);
    partial void Deletemedcin_info(medcin_info instance);
    partial void Insertproject_info(project_info instance);
    partial void Updateproject_info(project_info instance);
    partial void Deleteproject_info(project_info instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertdamage_person_tb(damage_person_tb instance);
    partial void Updatedamage_person_tb(damage_person_tb instance);
    partial void Deletedamage_person_tb(damage_person_tb instance);
    partial void Insertcar_damage(car_damage instance);
    partial void Updatecar_damage(car_damage instance);
    partial void Deletecar_damage(car_damage instance);
    partial void Insertreal_estale_damage(real_estale_damage instance);
    partial void Updatereal_estale_damage(real_estale_damage instance);
    partial void Deletereal_estale_damage(real_estale_damage instance);
    partial void Insertmain_injuries_info(main_injuries_info instance);
    partial void Updatemain_injuries_info(main_injuries_info instance);
    partial void Deletemain_injuries_info(main_injuries_info instance);
    partial void Insertorg_table(org_table instance);
    partial void Updateorg_table(org_table instance);
    partial void Deleteorg_table(org_table instance);
    partial void Insertmititary_info(mititary_info instance);
    partial void Updatemititary_info(mititary_info instance);
    partial void Deletemititary_info(mititary_info instance);
    #endregion
		
		public UNClassesDataContext() : 
				base(global::UN.Properties.Settings.Default.UNdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UNClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UNClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UNClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UNClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<medcin_info> medcin_infos
		{
			get
			{
				return this.GetTable<medcin_info>();
			}
		}
		
		public System.Data.Linq.Table<project_info> project_infos
		{
			get
			{
				return this.GetTable<project_info>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<damage_person_tb> damage_person_tbs
		{
			get
			{
				return this.GetTable<damage_person_tb>();
			}
		}
		
		public System.Data.Linq.Table<car_damage> car_damages
		{
			get
			{
				return this.GetTable<car_damage>();
			}
		}
		
		public System.Data.Linq.Table<real_estale_damage> real_estale_damages
		{
			get
			{
				return this.GetTable<real_estale_damage>();
			}
		}
		
		public System.Data.Linq.Table<main_injuries_info> main_injuries_infos
		{
			get
			{
				return this.GetTable<main_injuries_info>();
			}
		}
		
		public System.Data.Linq.Table<org_table> org_tables
		{
			get
			{
				return this.GetTable<org_table>();
			}
		}
		
		public System.Data.Linq.Table<mititary_info> mititary_infos
		{
			get
			{
				return this.GetTable<mititary_info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.medcin_info")]
	public partial class medcin_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _m_id;
		
		private string _national_num;
		
		private string _injury_type;
		
		private string _Deficit_ratio;
		
		private string _injury_details;
		
		private System.Nullable<bool> _is_self_rely;
		
		private System.Nullable<bool> _is_Permanent_disability;
		
		private System.Nullable<bool> _is_Permanent_care;
		
		private string _how_to_Execution;
		
		private System.Nullable<bool> _another_helps;
		
		private string _who_helps;
		
		private EntityRef<main_injuries_info> _main_injuries_info;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onm_idChanging(int value);
    partial void Onm_idChanged();
    partial void Onnational_numChanging(string value);
    partial void Onnational_numChanged();
    partial void Oninjury_typeChanging(string value);
    partial void Oninjury_typeChanged();
    partial void OnDeficit_ratioChanging(string value);
    partial void OnDeficit_ratioChanged();
    partial void Oninjury_detailsChanging(string value);
    partial void Oninjury_detailsChanged();
    partial void Onis_self_relyChanging(System.Nullable<bool> value);
    partial void Onis_self_relyChanged();
    partial void Onis_Permanent_disabilityChanging(System.Nullable<bool> value);
    partial void Onis_Permanent_disabilityChanged();
    partial void Onis_Permanent_careChanging(System.Nullable<bool> value);
    partial void Onis_Permanent_careChanged();
    partial void Onhow_to_ExecutionChanging(string value);
    partial void Onhow_to_ExecutionChanged();
    partial void Onanother_helpsChanging(System.Nullable<bool> value);
    partial void Onanother_helpsChanged();
    partial void Onwho_helpsChanging(string value);
    partial void Onwho_helpsChanged();
    #endregion
		
		public medcin_info()
		{
			this._main_injuries_info = default(EntityRef<main_injuries_info>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int m_id
		{
			get
			{
				return this._m_id;
			}
			set
			{
				if ((this._m_id != value))
				{
					this.Onm_idChanging(value);
					this.SendPropertyChanging();
					this._m_id = value;
					this.SendPropertyChanged("m_id");
					this.Onm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_num", DbType="VarChar(50)")]
		public string national_num
		{
			get
			{
				return this._national_num;
			}
			set
			{
				if ((this._national_num != value))
				{
					if (this._main_injuries_info.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnational_numChanging(value);
					this.SendPropertyChanging();
					this._national_num = value;
					this.SendPropertyChanged("national_num");
					this.Onnational_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_injury_type", DbType="VarChar(50)")]
		public string injury_type
		{
			get
			{
				return this._injury_type;
			}
			set
			{
				if ((this._injury_type != value))
				{
					this.Oninjury_typeChanging(value);
					this.SendPropertyChanging();
					this._injury_type = value;
					this.SendPropertyChanged("injury_type");
					this.Oninjury_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deficit_ratio", DbType="VarChar(50)")]
		public string Deficit_ratio
		{
			get
			{
				return this._Deficit_ratio;
			}
			set
			{
				if ((this._Deficit_ratio != value))
				{
					this.OnDeficit_ratioChanging(value);
					this.SendPropertyChanging();
					this._Deficit_ratio = value;
					this.SendPropertyChanged("Deficit_ratio");
					this.OnDeficit_ratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_injury_details", DbType="VarChar(50)")]
		public string injury_details
		{
			get
			{
				return this._injury_details;
			}
			set
			{
				if ((this._injury_details != value))
				{
					this.Oninjury_detailsChanging(value);
					this.SendPropertyChanging();
					this._injury_details = value;
					this.SendPropertyChanged("injury_details");
					this.Oninjury_detailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_self_rely", DbType="Bit")]
		public System.Nullable<bool> is_self_rely
		{
			get
			{
				return this._is_self_rely;
			}
			set
			{
				if ((this._is_self_rely != value))
				{
					this.Onis_self_relyChanging(value);
					this.SendPropertyChanging();
					this._is_self_rely = value;
					this.SendPropertyChanged("is_self_rely");
					this.Onis_self_relyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_Permanent_disability", DbType="Bit")]
		public System.Nullable<bool> is_Permanent_disability
		{
			get
			{
				return this._is_Permanent_disability;
			}
			set
			{
				if ((this._is_Permanent_disability != value))
				{
					this.Onis_Permanent_disabilityChanging(value);
					this.SendPropertyChanging();
					this._is_Permanent_disability = value;
					this.SendPropertyChanged("is_Permanent_disability");
					this.Onis_Permanent_disabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_Permanent_care", DbType="Bit")]
		public System.Nullable<bool> is_Permanent_care
		{
			get
			{
				return this._is_Permanent_care;
			}
			set
			{
				if ((this._is_Permanent_care != value))
				{
					this.Onis_Permanent_careChanging(value);
					this.SendPropertyChanging();
					this._is_Permanent_care = value;
					this.SendPropertyChanged("is_Permanent_care");
					this.Onis_Permanent_careChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_how_to_Execution", DbType="VarChar(50)")]
		public string how_to_Execution
		{
			get
			{
				return this._how_to_Execution;
			}
			set
			{
				if ((this._how_to_Execution != value))
				{
					this.Onhow_to_ExecutionChanging(value);
					this.SendPropertyChanging();
					this._how_to_Execution = value;
					this.SendPropertyChanged("how_to_Execution");
					this.Onhow_to_ExecutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_another_helps", DbType="Bit")]
		public System.Nullable<bool> another_helps
		{
			get
			{
				return this._another_helps;
			}
			set
			{
				if ((this._another_helps != value))
				{
					this.Onanother_helpsChanging(value);
					this.SendPropertyChanging();
					this._another_helps = value;
					this.SendPropertyChanged("another_helps");
					this.Onanother_helpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_who_helps", DbType="VarChar(50)")]
		public string who_helps
		{
			get
			{
				return this._who_helps;
			}
			set
			{
				if ((this._who_helps != value))
				{
					this.Onwho_helpsChanging(value);
					this.SendPropertyChanging();
					this._who_helps = value;
					this.SendPropertyChanged("who_helps");
					this.Onwho_helpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="main_injuries_info_medcin_info", Storage="_main_injuries_info", ThisKey="national_num", OtherKey="national_num", IsForeignKey=true)]
		public main_injuries_info main_injuries_info
		{
			get
			{
				return this._main_injuries_info.Entity;
			}
			set
			{
				main_injuries_info previousValue = this._main_injuries_info.Entity;
				if (((previousValue != value) 
							|| (this._main_injuries_info.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._main_injuries_info.Entity = null;
						previousValue.medcin_infos.Remove(this);
					}
					this._main_injuries_info.Entity = value;
					if ((value != null))
					{
						value.medcin_infos.Add(this);
						this._national_num = value.national_num;
					}
					else
					{
						this._national_num = default(string);
					}
					this.SendPropertyChanged("main_injuries_info");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.project_info")]
	public partial class project_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _project_id;
		
		private string _national_num;
		
		private string _mony_amount;
		
		private string _given_side;
		
		private string _given_date;
		
		private EntityRef<main_injuries_info> _main_injuries_info;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproject_idChanging(int value);
    partial void Onproject_idChanged();
    partial void Onnational_numChanging(string value);
    partial void Onnational_numChanged();
    partial void Onmony_amountChanging(string value);
    partial void Onmony_amountChanged();
    partial void Ongiven_sideChanging(string value);
    partial void Ongiven_sideChanged();
    partial void Ongiven_dateChanging(string value);
    partial void Ongiven_dateChanged();
    #endregion
		
		public project_info()
		{
			this._main_injuries_info = default(EntityRef<main_injuries_info>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int project_id
		{
			get
			{
				return this._project_id;
			}
			set
			{
				if ((this._project_id != value))
				{
					this.Onproject_idChanging(value);
					this.SendPropertyChanging();
					this._project_id = value;
					this.SendPropertyChanged("project_id");
					this.Onproject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_num", DbType="VarChar(50)")]
		public string national_num
		{
			get
			{
				return this._national_num;
			}
			set
			{
				if ((this._national_num != value))
				{
					if (this._main_injuries_info.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnational_numChanging(value);
					this.SendPropertyChanging();
					this._national_num = value;
					this.SendPropertyChanged("national_num");
					this.Onnational_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mony_amount", DbType="VarChar(50)")]
		public string mony_amount
		{
			get
			{
				return this._mony_amount;
			}
			set
			{
				if ((this._mony_amount != value))
				{
					this.Onmony_amountChanging(value);
					this.SendPropertyChanging();
					this._mony_amount = value;
					this.SendPropertyChanged("mony_amount");
					this.Onmony_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_given_side", DbType="VarChar(50)")]
		public string given_side
		{
			get
			{
				return this._given_side;
			}
			set
			{
				if ((this._given_side != value))
				{
					this.Ongiven_sideChanging(value);
					this.SendPropertyChanging();
					this._given_side = value;
					this.SendPropertyChanged("given_side");
					this.Ongiven_sideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_given_date", DbType="VarChar(50)")]
		public string given_date
		{
			get
			{
				return this._given_date;
			}
			set
			{
				if ((this._given_date != value))
				{
					this.Ongiven_dateChanging(value);
					this.SendPropertyChanging();
					this._given_date = value;
					this.SendPropertyChanged("given_date");
					this.Ongiven_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="main_injuries_info_project_info", Storage="_main_injuries_info", ThisKey="national_num", OtherKey="national_num", IsForeignKey=true)]
		public main_injuries_info main_injuries_info
		{
			get
			{
				return this._main_injuries_info.Entity;
			}
			set
			{
				main_injuries_info previousValue = this._main_injuries_info.Entity;
				if (((previousValue != value) 
							|| (this._main_injuries_info.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._main_injuries_info.Entity = null;
						previousValue.project_infos.Remove(this);
					}
					this._main_injuries_info.Entity = value;
					if ((value != null))
					{
						value.project_infos.Add(this);
						this._national_num = value.national_num;
					}
					else
					{
						this._national_num = default(string);
					}
					this.SendPropertyChanged("main_injuries_info");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.damage_person_tb")]
	public partial class damage_person_tb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _mother_name;
		
		private string _national_number_type;
		
		private string _national_number;
		
		private string _phone_number;
		
		private string _quarter;
		
		private EntitySet<car_damage> _car_damages;
		
		private EntitySet<real_estale_damage> _real_estale_damages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onmother_nameChanging(string value);
    partial void Onmother_nameChanged();
    partial void Onnational_number_typeChanging(string value);
    partial void Onnational_number_typeChanged();
    partial void Onnational_numberChanging(string value);
    partial void Onnational_numberChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void OnquarterChanging(string value);
    partial void OnquarterChanged();
    #endregion
		
		public damage_person_tb()
		{
			this._car_damages = new EntitySet<car_damage>(new Action<car_damage>(this.attach_car_damages), new Action<car_damage>(this.detach_car_damages));
			this._real_estale_damages = new EntitySet<real_estale_damage>(new Action<real_estale_damage>(this.attach_real_estale_damages), new Action<real_estale_damage>(this.detach_real_estale_damages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mother_name", DbType="VarChar(50)")]
		public string mother_name
		{
			get
			{
				return this._mother_name;
			}
			set
			{
				if ((this._mother_name != value))
				{
					this.Onmother_nameChanging(value);
					this.SendPropertyChanging();
					this._mother_name = value;
					this.SendPropertyChanged("mother_name");
					this.Onmother_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_number_type", DbType="VarChar(MAX)")]
		public string national_number_type
		{
			get
			{
				return this._national_number_type;
			}
			set
			{
				if ((this._national_number_type != value))
				{
					this.Onnational_number_typeChanging(value);
					this.SendPropertyChanging();
					this._national_number_type = value;
					this.SendPropertyChanged("national_number_type");
					this.Onnational_number_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_number", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string national_number
		{
			get
			{
				return this._national_number;
			}
			set
			{
				if ((this._national_number != value))
				{
					this.Onnational_numberChanging(value);
					this.SendPropertyChanging();
					this._national_number = value;
					this.SendPropertyChanged("national_number");
					this.Onnational_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(50)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quarter", DbType="VarChar(50)")]
		public string quarter
		{
			get
			{
				return this._quarter;
			}
			set
			{
				if ((this._quarter != value))
				{
					this.OnquarterChanging(value);
					this.SendPropertyChanging();
					this._quarter = value;
					this.SendPropertyChanged("quarter");
					this.OnquarterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="damage_person_tb_car_damage", Storage="_car_damages", ThisKey="national_number", OtherKey="national_number")]
		public EntitySet<car_damage> car_damages
		{
			get
			{
				return this._car_damages;
			}
			set
			{
				this._car_damages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="damage_person_tb_real_estale_damage", Storage="_real_estale_damages", ThisKey="national_number", OtherKey="national_number")]
		public EntitySet<real_estale_damage> real_estale_damages
		{
			get
			{
				return this._real_estale_damages;
			}
			set
			{
				this._real_estale_damages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_car_damages(car_damage entity)
		{
			this.SendPropertyChanging();
			entity.damage_person_tb = this;
		}
		
		private void detach_car_damages(car_damage entity)
		{
			this.SendPropertyChanging();
			entity.damage_person_tb = null;
		}
		
		private void attach_real_estale_damages(real_estale_damage entity)
		{
			this.SendPropertyChanging();
			entity.damage_person_tb = this;
		}
		
		private void detach_real_estale_damages(real_estale_damage entity)
		{
			this.SendPropertyChanging();
			entity.damage_person_tb = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.car_damage")]
	public partial class car_damage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _national_number;
		
		private int _c_id;
		
		private string _city;
		
		private string _number;
		
		private string _type;
		
		private System.Nullable<int> _year;
		
		private string _category;
		
		private string _damage_type;
		
		private string _damage_value;
		
		private string _comp_worth_number;
		
		private string _comp_worth_text;
		
		private EntityRef<damage_person_tb> _damage_person_tb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnational_numberChanging(string value);
    partial void Onnational_numberChanged();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnnumberChanging(string value);
    partial void OnnumberChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void Ondamage_typeChanging(string value);
    partial void Ondamage_typeChanged();
    partial void Ondamage_valueChanging(string value);
    partial void Ondamage_valueChanged();
    partial void Oncomp_worth_numberChanging(string value);
    partial void Oncomp_worth_numberChanged();
    partial void Oncomp_worth_textChanging(string value);
    partial void Oncomp_worth_textChanged();
    #endregion
		
		public car_damage()
		{
			this._damage_person_tb = default(EntityRef<damage_person_tb>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_number", DbType="VarChar(50)")]
		public string national_number
		{
			get
			{
				return this._national_number;
			}
			set
			{
				if ((this._national_number != value))
				{
					if (this._damage_person_tb.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnational_numberChanging(value);
					this.SendPropertyChanging();
					this._national_number = value;
					this.SendPropertyChanged("national_number");
					this.Onnational_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_damage_type", DbType="VarChar(50)")]
		public string damage_type
		{
			get
			{
				return this._damage_type;
			}
			set
			{
				if ((this._damage_type != value))
				{
					this.Ondamage_typeChanging(value);
					this.SendPropertyChanging();
					this._damage_type = value;
					this.SendPropertyChanged("damage_type");
					this.Ondamage_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_damage_value", DbType="VarChar(50)")]
		public string damage_value
		{
			get
			{
				return this._damage_value;
			}
			set
			{
				if ((this._damage_value != value))
				{
					this.Ondamage_valueChanging(value);
					this.SendPropertyChanging();
					this._damage_value = value;
					this.SendPropertyChanged("damage_value");
					this.Ondamage_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp_worth_number", DbType="VarChar(50)")]
		public string comp_worth_number
		{
			get
			{
				return this._comp_worth_number;
			}
			set
			{
				if ((this._comp_worth_number != value))
				{
					this.Oncomp_worth_numberChanging(value);
					this.SendPropertyChanging();
					this._comp_worth_number = value;
					this.SendPropertyChanged("comp_worth_number");
					this.Oncomp_worth_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp_worth_text", DbType="VarChar(MAX)")]
		public string comp_worth_text
		{
			get
			{
				return this._comp_worth_text;
			}
			set
			{
				if ((this._comp_worth_text != value))
				{
					this.Oncomp_worth_textChanging(value);
					this.SendPropertyChanging();
					this._comp_worth_text = value;
					this.SendPropertyChanged("comp_worth_text");
					this.Oncomp_worth_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="damage_person_tb_car_damage", Storage="_damage_person_tb", ThisKey="national_number", OtherKey="national_number", IsForeignKey=true)]
		public damage_person_tb damage_person_tb
		{
			get
			{
				return this._damage_person_tb.Entity;
			}
			set
			{
				damage_person_tb previousValue = this._damage_person_tb.Entity;
				if (((previousValue != value) 
							|| (this._damage_person_tb.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._damage_person_tb.Entity = null;
						previousValue.car_damages.Remove(this);
					}
					this._damage_person_tb.Entity = value;
					if ((value != null))
					{
						value.car_damages.Add(this);
						this._national_number = value.national_number;
					}
					else
					{
						this._national_number = default(string);
					}
					this.SendPropertyChanged("damage_person_tb");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.real_estale_damage")]
	public partial class real_estale_damage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _d_id;
		
		private string _national_number;
		
		private string _real_estate_id;
		
		private string _real_estale_place;
		
		private string _damage_value;
		
		private string _comp_worth;
		
		private string _electrical_equipment;
		
		private string _final_comp_int;
		
		private string _final_comp_text;
		
		private string _comp_accepted;
		
		private System.Nullable<bool> _real_review;
		
		private EntityRef<damage_person_tb> _damage_person_tb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ond_idChanging(int value);
    partial void Ond_idChanged();
    partial void Onnational_numberChanging(string value);
    partial void Onnational_numberChanged();
    partial void Onreal_estate_idChanging(string value);
    partial void Onreal_estate_idChanged();
    partial void Onreal_estale_placeChanging(string value);
    partial void Onreal_estale_placeChanged();
    partial void Ondamage_valueChanging(string value);
    partial void Ondamage_valueChanged();
    partial void Oncomp_worthChanging(string value);
    partial void Oncomp_worthChanged();
    partial void Onelectrical_equipmentChanging(string value);
    partial void Onelectrical_equipmentChanged();
    partial void Onfinal_comp_intChanging(string value);
    partial void Onfinal_comp_intChanged();
    partial void Onfinal_comp_textChanging(string value);
    partial void Onfinal_comp_textChanged();
    partial void Oncomp_acceptedChanging(string value);
    partial void Oncomp_acceptedChanged();
    partial void Onreal_reviewChanging(System.Nullable<bool> value);
    partial void Onreal_reviewChanged();
    #endregion
		
		public real_estale_damage()
		{
			this._damage_person_tb = default(EntityRef<damage_person_tb>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int d_id
		{
			get
			{
				return this._d_id;
			}
			set
			{
				if ((this._d_id != value))
				{
					this.Ond_idChanging(value);
					this.SendPropertyChanging();
					this._d_id = value;
					this.SendPropertyChanged("d_id");
					this.Ond_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_number", DbType="VarChar(50)")]
		public string national_number
		{
			get
			{
				return this._national_number;
			}
			set
			{
				if ((this._national_number != value))
				{
					if (this._damage_person_tb.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnational_numberChanging(value);
					this.SendPropertyChanging();
					this._national_number = value;
					this.SendPropertyChanged("national_number");
					this.Onnational_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_estate_id", DbType="VarChar(50)")]
		public string real_estate_id
		{
			get
			{
				return this._real_estate_id;
			}
			set
			{
				if ((this._real_estate_id != value))
				{
					this.Onreal_estate_idChanging(value);
					this.SendPropertyChanging();
					this._real_estate_id = value;
					this.SendPropertyChanged("real_estate_id");
					this.Onreal_estate_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_estale_place", DbType="VarChar(50)")]
		public string real_estale_place
		{
			get
			{
				return this._real_estale_place;
			}
			set
			{
				if ((this._real_estale_place != value))
				{
					this.Onreal_estale_placeChanging(value);
					this.SendPropertyChanging();
					this._real_estale_place = value;
					this.SendPropertyChanged("real_estale_place");
					this.Onreal_estale_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_damage_value", DbType="VarChar(50)")]
		public string damage_value
		{
			get
			{
				return this._damage_value;
			}
			set
			{
				if ((this._damage_value != value))
				{
					this.Ondamage_valueChanging(value);
					this.SendPropertyChanging();
					this._damage_value = value;
					this.SendPropertyChanged("damage_value");
					this.Ondamage_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp_worth", DbType="VarChar(50)")]
		public string comp_worth
		{
			get
			{
				return this._comp_worth;
			}
			set
			{
				if ((this._comp_worth != value))
				{
					this.Oncomp_worthChanging(value);
					this.SendPropertyChanging();
					this._comp_worth = value;
					this.SendPropertyChanged("comp_worth");
					this.Oncomp_worthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_electrical_equipment", DbType="VarChar(MAX)")]
		public string electrical_equipment
		{
			get
			{
				return this._electrical_equipment;
			}
			set
			{
				if ((this._electrical_equipment != value))
				{
					this.Onelectrical_equipmentChanging(value);
					this.SendPropertyChanging();
					this._electrical_equipment = value;
					this.SendPropertyChanged("electrical_equipment");
					this.Onelectrical_equipmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_comp_int", DbType="VarChar(MAX)")]
		public string final_comp_int
		{
			get
			{
				return this._final_comp_int;
			}
			set
			{
				if ((this._final_comp_int != value))
				{
					this.Onfinal_comp_intChanging(value);
					this.SendPropertyChanging();
					this._final_comp_int = value;
					this.SendPropertyChanged("final_comp_int");
					this.Onfinal_comp_intChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_comp_text", DbType="VarChar(MAX)")]
		public string final_comp_text
		{
			get
			{
				return this._final_comp_text;
			}
			set
			{
				if ((this._final_comp_text != value))
				{
					this.Onfinal_comp_textChanging(value);
					this.SendPropertyChanging();
					this._final_comp_text = value;
					this.SendPropertyChanged("final_comp_text");
					this.Onfinal_comp_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp_accepted", DbType="VarChar(MAX)")]
		public string comp_accepted
		{
			get
			{
				return this._comp_accepted;
			}
			set
			{
				if ((this._comp_accepted != value))
				{
					this.Oncomp_acceptedChanging(value);
					this.SendPropertyChanging();
					this._comp_accepted = value;
					this.SendPropertyChanged("comp_accepted");
					this.Oncomp_acceptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_review", DbType="Bit")]
		public System.Nullable<bool> real_review
		{
			get
			{
				return this._real_review;
			}
			set
			{
				if ((this._real_review != value))
				{
					this.Onreal_reviewChanging(value);
					this.SendPropertyChanging();
					this._real_review = value;
					this.SendPropertyChanged("real_review");
					this.Onreal_reviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="damage_person_tb_real_estale_damage", Storage="_damage_person_tb", ThisKey="national_number", OtherKey="national_number", IsForeignKey=true)]
		public damage_person_tb damage_person_tb
		{
			get
			{
				return this._damage_person_tb.Entity;
			}
			set
			{
				damage_person_tb previousValue = this._damage_person_tb.Entity;
				if (((previousValue != value) 
							|| (this._damage_person_tb.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._damage_person_tb.Entity = null;
						previousValue.real_estale_damages.Remove(this);
					}
					this._damage_person_tb.Entity = value;
					if ((value != null))
					{
						value.real_estale_damages.Add(this);
						this._national_number = value.national_number;
					}
					else
					{
						this._national_number = default(string);
					}
					this.SendPropertyChanged("damage_person_tb");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.main_injuries_info")]
	public partial class main_injuries_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _national_num_type;
		
		private string _national_num;
		
		private string _full_name;
		
		private string _m_name;
		
		private string _govern;
		
		private string _b_date;
		
		private string _family_state;
		
		private string _study_degree;
		
		private System.Nullable<int> _child_number;
		
		private string _phone_number;
		
		private System.Nullable<int> _family_number;
		
		private System.Nullable<bool> _is_owner;
		
		private string _house_state;
		
		private string _money_state;
		
		private string _another_funder;
		
		private string _live_place;
		
		private string _Restriction_num;
		
		private EntitySet<medcin_info> _medcin_infos;
		
		private EntitySet<project_info> _project_infos;
		
		private EntitySet<mititary_info> _mititary_infos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnational_num_typeChanging(string value);
    partial void Onnational_num_typeChanged();
    partial void Onnational_numChanging(string value);
    partial void Onnational_numChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    partial void Onm_nameChanging(string value);
    partial void Onm_nameChanged();
    partial void OngovernChanging(string value);
    partial void OngovernChanged();
    partial void Onb_dateChanging(string value);
    partial void Onb_dateChanged();
    partial void Onfamily_stateChanging(string value);
    partial void Onfamily_stateChanged();
    partial void Onstudy_degreeChanging(string value);
    partial void Onstudy_degreeChanged();
    partial void Onchild_numberChanging(System.Nullable<int> value);
    partial void Onchild_numberChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void Onfamily_numberChanging(System.Nullable<int> value);
    partial void Onfamily_numberChanged();
    partial void Onis_ownerChanging(System.Nullable<bool> value);
    partial void Onis_ownerChanged();
    partial void Onhouse_stateChanging(string value);
    partial void Onhouse_stateChanged();
    partial void Onmoney_stateChanging(string value);
    partial void Onmoney_stateChanged();
    partial void Onanother_funderChanging(string value);
    partial void Onanother_funderChanged();
    partial void Onlive_placeChanging(string value);
    partial void Onlive_placeChanged();
    partial void OnRestriction_numChanging(string value);
    partial void OnRestriction_numChanged();
    #endregion
		
		public main_injuries_info()
		{
			this._medcin_infos = new EntitySet<medcin_info>(new Action<medcin_info>(this.attach_medcin_infos), new Action<medcin_info>(this.detach_medcin_infos));
			this._project_infos = new EntitySet<project_info>(new Action<project_info>(this.attach_project_infos), new Action<project_info>(this.detach_project_infos));
			this._mititary_infos = new EntitySet<mititary_info>(new Action<mititary_info>(this.attach_mititary_infos), new Action<mititary_info>(this.detach_mititary_infos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_num_type", DbType="VarChar(50)")]
		public string national_num_type
		{
			get
			{
				return this._national_num_type;
			}
			set
			{
				if ((this._national_num_type != value))
				{
					this.Onnational_num_typeChanging(value);
					this.SendPropertyChanging();
					this._national_num_type = value;
					this.SendPropertyChanged("national_num_type");
					this.Onnational_num_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_num", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string national_num
		{
			get
			{
				return this._national_num;
			}
			set
			{
				if ((this._national_num != value))
				{
					this.Onnational_numChanging(value);
					this.SendPropertyChanging();
					this._national_num = value;
					this.SendPropertyChanged("national_num");
					this.Onnational_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="VarChar(50)")]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_name", DbType="VarChar(50)")]
		public string m_name
		{
			get
			{
				return this._m_name;
			}
			set
			{
				if ((this._m_name != value))
				{
					this.Onm_nameChanging(value);
					this.SendPropertyChanging();
					this._m_name = value;
					this.SendPropertyChanged("m_name");
					this.Onm_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_govern", DbType="VarChar(50)")]
		public string govern
		{
			get
			{
				return this._govern;
			}
			set
			{
				if ((this._govern != value))
				{
					this.OngovernChanging(value);
					this.SendPropertyChanging();
					this._govern = value;
					this.SendPropertyChanged("govern");
					this.OngovernChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_b_date", DbType="VarChar(50)")]
		public string b_date
		{
			get
			{
				return this._b_date;
			}
			set
			{
				if ((this._b_date != value))
				{
					this.Onb_dateChanging(value);
					this.SendPropertyChanging();
					this._b_date = value;
					this.SendPropertyChanged("b_date");
					this.Onb_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family_state", DbType="VarChar(50)")]
		public string family_state
		{
			get
			{
				return this._family_state;
			}
			set
			{
				if ((this._family_state != value))
				{
					this.Onfamily_stateChanging(value);
					this.SendPropertyChanging();
					this._family_state = value;
					this.SendPropertyChanged("family_state");
					this.Onfamily_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_study_degree", DbType="VarChar(50)")]
		public string study_degree
		{
			get
			{
				return this._study_degree;
			}
			set
			{
				if ((this._study_degree != value))
				{
					this.Onstudy_degreeChanging(value);
					this.SendPropertyChanging();
					this._study_degree = value;
					this.SendPropertyChanged("study_degree");
					this.Onstudy_degreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_child_number", DbType="Int")]
		public System.Nullable<int> child_number
		{
			get
			{
				return this._child_number;
			}
			set
			{
				if ((this._child_number != value))
				{
					this.Onchild_numberChanging(value);
					this.SendPropertyChanging();
					this._child_number = value;
					this.SendPropertyChanged("child_number");
					this.Onchild_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(50)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family_number", DbType="Int")]
		public System.Nullable<int> family_number
		{
			get
			{
				return this._family_number;
			}
			set
			{
				if ((this._family_number != value))
				{
					this.Onfamily_numberChanging(value);
					this.SendPropertyChanging();
					this._family_number = value;
					this.SendPropertyChanged("family_number");
					this.Onfamily_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_owner", DbType="Bit")]
		public System.Nullable<bool> is_owner
		{
			get
			{
				return this._is_owner;
			}
			set
			{
				if ((this._is_owner != value))
				{
					this.Onis_ownerChanging(value);
					this.SendPropertyChanging();
					this._is_owner = value;
					this.SendPropertyChanged("is_owner");
					this.Onis_ownerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_house_state", DbType="VarChar(50)")]
		public string house_state
		{
			get
			{
				return this._house_state;
			}
			set
			{
				if ((this._house_state != value))
				{
					this.Onhouse_stateChanging(value);
					this.SendPropertyChanging();
					this._house_state = value;
					this.SendPropertyChanged("house_state");
					this.Onhouse_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_money_state", DbType="VarChar(50)")]
		public string money_state
		{
			get
			{
				return this._money_state;
			}
			set
			{
				if ((this._money_state != value))
				{
					this.Onmoney_stateChanging(value);
					this.SendPropertyChanging();
					this._money_state = value;
					this.SendPropertyChanged("money_state");
					this.Onmoney_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_another_funder", DbType="VarChar(MAX)")]
		public string another_funder
		{
			get
			{
				return this._another_funder;
			}
			set
			{
				if ((this._another_funder != value))
				{
					this.Onanother_funderChanging(value);
					this.SendPropertyChanging();
					this._another_funder = value;
					this.SendPropertyChanged("another_funder");
					this.Onanother_funderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live_place", DbType="VarChar(50)")]
		public string live_place
		{
			get
			{
				return this._live_place;
			}
			set
			{
				if ((this._live_place != value))
				{
					this.Onlive_placeChanging(value);
					this.SendPropertyChanging();
					this._live_place = value;
					this.SendPropertyChanged("live_place");
					this.Onlive_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Restriction_num", DbType="VarChar(50)")]
		public string Restriction_num
		{
			get
			{
				return this._Restriction_num;
			}
			set
			{
				if ((this._Restriction_num != value))
				{
					this.OnRestriction_numChanging(value);
					this.SendPropertyChanging();
					this._Restriction_num = value;
					this.SendPropertyChanged("Restriction_num");
					this.OnRestriction_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="main_injuries_info_medcin_info", Storage="_medcin_infos", ThisKey="national_num", OtherKey="national_num")]
		public EntitySet<medcin_info> medcin_infos
		{
			get
			{
				return this._medcin_infos;
			}
			set
			{
				this._medcin_infos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="main_injuries_info_project_info", Storage="_project_infos", ThisKey="national_num", OtherKey="national_num")]
		public EntitySet<project_info> project_infos
		{
			get
			{
				return this._project_infos;
			}
			set
			{
				this._project_infos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="main_injuries_info_mititary_info", Storage="_mititary_infos", ThisKey="national_num", OtherKey="national_num")]
		public EntitySet<mititary_info> mititary_infos
		{
			get
			{
				return this._mititary_infos;
			}
			set
			{
				this._mititary_infos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_medcin_infos(medcin_info entity)
		{
			this.SendPropertyChanging();
			entity.main_injuries_info = this;
		}
		
		private void detach_medcin_infos(medcin_info entity)
		{
			this.SendPropertyChanging();
			entity.main_injuries_info = null;
		}
		
		private void attach_project_infos(project_info entity)
		{
			this.SendPropertyChanging();
			entity.main_injuries_info = this;
		}
		
		private void detach_project_infos(project_info entity)
		{
			this.SendPropertyChanging();
			entity.main_injuries_info = null;
		}
		
		private void attach_mititary_infos(mititary_info entity)
		{
			this.SendPropertyChanging();
			entity.main_injuries_info = this;
		}
		
		private void detach_mititary_infos(mititary_info entity)
		{
			this.SendPropertyChanging();
			entity.main_injuries_info = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.org_table")]
	public partial class org_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ord_id;
		
		private string _org_name;
		
		private string _coming_date;
		
		private string _visit_date;
		
		private string _visit_purpose;
		
		private string _visitor_name;
		
		private System.Nullable<bool> _visit_state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onord_idChanging(int value);
    partial void Onord_idChanged();
    partial void Onorg_nameChanging(string value);
    partial void Onorg_nameChanged();
    partial void Oncoming_dateChanging(string value);
    partial void Oncoming_dateChanged();
    partial void Onvisit_dateChanging(string value);
    partial void Onvisit_dateChanged();
    partial void Onvisit_purposeChanging(string value);
    partial void Onvisit_purposeChanged();
    partial void Onvisitor_nameChanging(string value);
    partial void Onvisitor_nameChanged();
    partial void Onvisit_stateChanging(System.Nullable<bool> value);
    partial void Onvisit_stateChanged();
    #endregion
		
		public org_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ord_id
		{
			get
			{
				return this._ord_id;
			}
			set
			{
				if ((this._ord_id != value))
				{
					this.Onord_idChanging(value);
					this.SendPropertyChanging();
					this._ord_id = value;
					this.SendPropertyChanged("ord_id");
					this.Onord_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_name", DbType="VarChar(50)")]
		public string org_name
		{
			get
			{
				return this._org_name;
			}
			set
			{
				if ((this._org_name != value))
				{
					this.Onorg_nameChanging(value);
					this.SendPropertyChanging();
					this._org_name = value;
					this.SendPropertyChanged("org_name");
					this.Onorg_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coming_date", DbType="VarChar(50)")]
		public string coming_date
		{
			get
			{
				return this._coming_date;
			}
			set
			{
				if ((this._coming_date != value))
				{
					this.Oncoming_dateChanging(value);
					this.SendPropertyChanging();
					this._coming_date = value;
					this.SendPropertyChanged("coming_date");
					this.Oncoming_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_date", DbType="VarChar(50)")]
		public string visit_date
		{
			get
			{
				return this._visit_date;
			}
			set
			{
				if ((this._visit_date != value))
				{
					this.Onvisit_dateChanging(value);
					this.SendPropertyChanging();
					this._visit_date = value;
					this.SendPropertyChanged("visit_date");
					this.Onvisit_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_purpose", DbType="VarChar(MAX)")]
		public string visit_purpose
		{
			get
			{
				return this._visit_purpose;
			}
			set
			{
				if ((this._visit_purpose != value))
				{
					this.Onvisit_purposeChanging(value);
					this.SendPropertyChanging();
					this._visit_purpose = value;
					this.SendPropertyChanged("visit_purpose");
					this.Onvisit_purposeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitor_name", DbType="VarChar(50)")]
		public string visitor_name
		{
			get
			{
				return this._visitor_name;
			}
			set
			{
				if ((this._visitor_name != value))
				{
					this.Onvisitor_nameChanging(value);
					this.SendPropertyChanging();
					this._visitor_name = value;
					this.SendPropertyChanged("visitor_name");
					this.Onvisitor_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_state", DbType="Bit")]
		public System.Nullable<bool> visit_state
		{
			get
			{
				return this._visit_state;
			}
			set
			{
				if ((this._visit_state != value))
				{
					this.Onvisit_stateChanging(value);
					this.SendPropertyChanging();
					this._visit_state = value;
					this.SendPropertyChanged("visit_state");
					this.Onvisit_stateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mititary_info")]
	public partial class mititary_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _military_id;
		
		private string _national_num;
		
		private string _service_side;
		
		private string _rank;
		
		private string _inrol_date;
		
		private string _injury_date;
		
		private string _miltary_number;
		
		private string _salary;
		
		private string _compan_injury;
		
		private string _injury_type;
		
		private string _Deficit_ratio;
		
		private string _injury_details;
		
		private string _who_helps;
		
		private System.Nullable<bool> _is_self_rely;
		
		private System.Nullable<bool> _is_permanent_disability;
		
		private System.Nullable<bool> _is_permanent_care;
		
		private System.Nullable<bool> _another_helps;
		
		private string _how_to_Execution;
		
		private EntityRef<main_injuries_info> _main_injuries_info;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmilitary_idChanging(int value);
    partial void Onmilitary_idChanged();
    partial void Onnational_numChanging(string value);
    partial void Onnational_numChanged();
    partial void Onservice_sideChanging(string value);
    partial void Onservice_sideChanged();
    partial void OnrankChanging(string value);
    partial void OnrankChanged();
    partial void Oninrol_dateChanging(string value);
    partial void Oninrol_dateChanged();
    partial void Oninjury_dateChanging(string value);
    partial void Oninjury_dateChanged();
    partial void Onmiltary_numberChanging(string value);
    partial void Onmiltary_numberChanged();
    partial void OnsalaryChanging(string value);
    partial void OnsalaryChanged();
    partial void Oncompan_injuryChanging(string value);
    partial void Oncompan_injuryChanged();
    partial void Oninjury_typeChanging(string value);
    partial void Oninjury_typeChanged();
    partial void OnDeficit_ratioChanging(string value);
    partial void OnDeficit_ratioChanged();
    partial void Oninjury_detailsChanging(string value);
    partial void Oninjury_detailsChanged();
    partial void Onwho_helpsChanging(string value);
    partial void Onwho_helpsChanged();
    partial void Onis_self_relyChanging(System.Nullable<bool> value);
    partial void Onis_self_relyChanged();
    partial void Onis_permanent_disabilityChanging(System.Nullable<bool> value);
    partial void Onis_permanent_disabilityChanged();
    partial void Onis_permanent_careChanging(System.Nullable<bool> value);
    partial void Onis_permanent_careChanged();
    partial void Onanother_helpsChanging(System.Nullable<bool> value);
    partial void Onanother_helpsChanged();
    partial void Onhow_to_ExecutionChanging(string value);
    partial void Onhow_to_ExecutionChanged();
    #endregion
		
		public mititary_info()
		{
			this._main_injuries_info = default(EntityRef<main_injuries_info>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_military_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int military_id
		{
			get
			{
				return this._military_id;
			}
			set
			{
				if ((this._military_id != value))
				{
					this.Onmilitary_idChanging(value);
					this.SendPropertyChanging();
					this._military_id = value;
					this.SendPropertyChanged("military_id");
					this.Onmilitary_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_national_num", DbType="VarChar(50)")]
		public string national_num
		{
			get
			{
				return this._national_num;
			}
			set
			{
				if ((this._national_num != value))
				{
					if (this._main_injuries_info.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnational_numChanging(value);
					this.SendPropertyChanging();
					this._national_num = value;
					this.SendPropertyChanged("national_num");
					this.Onnational_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_side", DbType="VarChar(50)")]
		public string service_side
		{
			get
			{
				return this._service_side;
			}
			set
			{
				if ((this._service_side != value))
				{
					this.Onservice_sideChanging(value);
					this.SendPropertyChanging();
					this._service_side = value;
					this.SendPropertyChanged("service_side");
					this.Onservice_sideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rank", DbType="VarChar(50)")]
		public string rank
		{
			get
			{
				return this._rank;
			}
			set
			{
				if ((this._rank != value))
				{
					this.OnrankChanging(value);
					this.SendPropertyChanging();
					this._rank = value;
					this.SendPropertyChanged("rank");
					this.OnrankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inrol_date", DbType="VarChar(50)")]
		public string inrol_date
		{
			get
			{
				return this._inrol_date;
			}
			set
			{
				if ((this._inrol_date != value))
				{
					this.Oninrol_dateChanging(value);
					this.SendPropertyChanging();
					this._inrol_date = value;
					this.SendPropertyChanged("inrol_date");
					this.Oninrol_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_injury_date", DbType="VarChar(50)")]
		public string injury_date
		{
			get
			{
				return this._injury_date;
			}
			set
			{
				if ((this._injury_date != value))
				{
					this.Oninjury_dateChanging(value);
					this.SendPropertyChanging();
					this._injury_date = value;
					this.SendPropertyChanged("injury_date");
					this.Oninjury_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miltary_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string miltary_number
		{
			get
			{
				return this._miltary_number;
			}
			set
			{
				if ((this._miltary_number != value))
				{
					this.Onmiltary_numberChanging(value);
					this.SendPropertyChanging();
					this._miltary_number = value;
					this.SendPropertyChanged("miltary_number");
					this.Onmiltary_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(50)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compan_injury", DbType="VarChar(50)")]
		public string compan_injury
		{
			get
			{
				return this._compan_injury;
			}
			set
			{
				if ((this._compan_injury != value))
				{
					this.Oncompan_injuryChanging(value);
					this.SendPropertyChanging();
					this._compan_injury = value;
					this.SendPropertyChanged("compan_injury");
					this.Oncompan_injuryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_injury_type", DbType="VarChar(50)")]
		public string injury_type
		{
			get
			{
				return this._injury_type;
			}
			set
			{
				if ((this._injury_type != value))
				{
					this.Oninjury_typeChanging(value);
					this.SendPropertyChanging();
					this._injury_type = value;
					this.SendPropertyChanged("injury_type");
					this.Oninjury_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deficit_ratio", DbType="VarChar(50)")]
		public string Deficit_ratio
		{
			get
			{
				return this._Deficit_ratio;
			}
			set
			{
				if ((this._Deficit_ratio != value))
				{
					this.OnDeficit_ratioChanging(value);
					this.SendPropertyChanging();
					this._Deficit_ratio = value;
					this.SendPropertyChanged("Deficit_ratio");
					this.OnDeficit_ratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_injury_details", DbType="VarChar(50)")]
		public string injury_details
		{
			get
			{
				return this._injury_details;
			}
			set
			{
				if ((this._injury_details != value))
				{
					this.Oninjury_detailsChanging(value);
					this.SendPropertyChanging();
					this._injury_details = value;
					this.SendPropertyChanged("injury_details");
					this.Oninjury_detailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_who_helps", DbType="VarChar(50)")]
		public string who_helps
		{
			get
			{
				return this._who_helps;
			}
			set
			{
				if ((this._who_helps != value))
				{
					this.Onwho_helpsChanging(value);
					this.SendPropertyChanging();
					this._who_helps = value;
					this.SendPropertyChanged("who_helps");
					this.Onwho_helpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_self_rely", DbType="Bit")]
		public System.Nullable<bool> is_self_rely
		{
			get
			{
				return this._is_self_rely;
			}
			set
			{
				if ((this._is_self_rely != value))
				{
					this.Onis_self_relyChanging(value);
					this.SendPropertyChanging();
					this._is_self_rely = value;
					this.SendPropertyChanged("is_self_rely");
					this.Onis_self_relyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_permanent_disability", DbType="Bit")]
		public System.Nullable<bool> is_permanent_disability
		{
			get
			{
				return this._is_permanent_disability;
			}
			set
			{
				if ((this._is_permanent_disability != value))
				{
					this.Onis_permanent_disabilityChanging(value);
					this.SendPropertyChanging();
					this._is_permanent_disability = value;
					this.SendPropertyChanged("is_permanent_disability");
					this.Onis_permanent_disabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_permanent_care", DbType="Bit")]
		public System.Nullable<bool> is_permanent_care
		{
			get
			{
				return this._is_permanent_care;
			}
			set
			{
				if ((this._is_permanent_care != value))
				{
					this.Onis_permanent_careChanging(value);
					this.SendPropertyChanging();
					this._is_permanent_care = value;
					this.SendPropertyChanged("is_permanent_care");
					this.Onis_permanent_careChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_another_helps", DbType="Bit")]
		public System.Nullable<bool> another_helps
		{
			get
			{
				return this._another_helps;
			}
			set
			{
				if ((this._another_helps != value))
				{
					this.Onanother_helpsChanging(value);
					this.SendPropertyChanging();
					this._another_helps = value;
					this.SendPropertyChanged("another_helps");
					this.Onanother_helpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_how_to_Execution", DbType="VarChar(MAX)")]
		public string how_to_Execution
		{
			get
			{
				return this._how_to_Execution;
			}
			set
			{
				if ((this._how_to_Execution != value))
				{
					this.Onhow_to_ExecutionChanging(value);
					this.SendPropertyChanging();
					this._how_to_Execution = value;
					this.SendPropertyChanged("how_to_Execution");
					this.Onhow_to_ExecutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="main_injuries_info_mititary_info", Storage="_main_injuries_info", ThisKey="national_num", OtherKey="national_num", IsForeignKey=true)]
		public main_injuries_info main_injuries_info
		{
			get
			{
				return this._main_injuries_info.Entity;
			}
			set
			{
				main_injuries_info previousValue = this._main_injuries_info.Entity;
				if (((previousValue != value) 
							|| (this._main_injuries_info.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._main_injuries_info.Entity = null;
						previousValue.mititary_infos.Remove(this);
					}
					this._main_injuries_info.Entity = value;
					if ((value != null))
					{
						value.mititary_infos.Add(this);
						this._national_num = value.national_num;
					}
					else
					{
						this._national_num = default(string);
					}
					this.SendPropertyChanged("main_injuries_info");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
